FROM alpine:3.20

RUN apk add --no-cache openssh-server shadow bash \
    && ssh-keygen -A

COPY podspawn /usr/local/bin/podspawn
RUN chmod +x /usr/local/bin/podspawn

COPY config.yaml /etc/podspawn/config.yaml

RUN mkdir -p /etc/podspawn/keys \
    && mkdir -p /var/lib/podspawn/locks \
    && chmod 1777 /var/lib/podspawn \
    && chmod 1777 /var/lib/podspawn/locks \
    && touch /var/log/podspawn.log \
    && chmod 666 /var/log/podspawn.log

EXPOSE 22
CMD chmod 666 /var/run/docker.sock && umask 0000 && exec /usr/sbin/sshd -D -e
